In [1]:
import numpy as np

# array이용 ndarray 생성

In [2]:
arr = np.array([1, 2, 3, 4])   # 1차원 배열

In [3]:
arr2 = np.array([ [1, 2],[3, 4], [5, 6] ])   # 2차원 배열(3행 2열)

In [4]:
arr3 = np.array([[ [1, 2], [3, 4], [5, 6] ]])  # 3차원 배열(1면 3행 2열)

In [5]:
ex1 = np.array([10])   # 대괄호가 1개 : 1차원 배열

In [6]:
ex2 = np.array([[10]])   # 대괄호가 2개 : 2차원 배열

In [7]:
ex1.shape   # shape : 차원 확인(튜플형태)

(1,)

In [8]:
ex2.shape

(1, 1)

In [9]:
arr = np.arange(1, 11)   # arange(시작값, 마지막값) : 시작값부터 마지막 - 1까지

In [10]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr = np.empty((2, 3))   # 비어있는 행열 생성

In [12]:
arr

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.05695252e-307, 1.42419938e-306, 7.56603881e-307]])

In [13]:
arr = np.ones((2, 3))   # ones : 1(실수)로 초기화한 후 배열 생성

In [14]:
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
type(arr)

numpy.ndarray

In [16]:
arr.dtype   # dtype : dataType확인

dtype('float64')

In [17]:
arr = np.empty((2, 3))   # 초기화 할 경우 empty로 생성 시 초기화 된 값으로 초기화됨

In [18]:
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
arr = np.zeros((2, 3))   # zeros : 0(실수)로 초기화한 후 배열 생성

In [20]:
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
arr = np.full((2, 3), 5)   # full((행,열), 값) : 값으로 다 채운 배열 생성

In [22]:
arr

array([[5, 5, 5],
       [5, 5, 5]])

In [23]:
arr.dtype

dtype('int32')

In [24]:
arr = np.eye(5)   # eye : 배열의 행의 개수와 열의 개수가 같은 배열 생성(단위행렬)

In [25]:
# 행과 열이 같은 위치는 1, 나머지는 0으로 채워짐

In [26]:
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
arr.dtype

dtype('float64')

In [28]:
arr.astype(np.int32)   #astype : 타입을 변경

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [29]:
# astype으로 타입 변경 시 변수에 저장하지 않으면 다시 돌아감

In [30]:
arr = arr.astype(np.int32)

In [31]:
arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [32]:
arr.dtype

dtype('int32')

In [33]:
arr = arr.astype(np.int16)

In [34]:
arr.dtype

dtype('int16')

In [35]:
arr.size   # size : 배열의 요소의 개수

25

In [36]:
arr.itemsize   # itemsize : 배열요소의 데이터사이즈

2

In [37]:
# int 16 = 16bit = 2byte

In [38]:
arr = arr.astype(np.int64)

In [39]:
arr.dtype

dtype('int64')

In [40]:
arr.itemsize   # int 64 = 64bit = 8byte

8

In [41]:
np.size(arr)

25

속성 사용 => 배열명.속성명  
ex) arr.size  
함수 사용 => 모듈명.함수명(배열명)  
np.size(arr)  

In [42]:
arr = np.array([1, 2, 3])

In [43]:
arr.dtype

dtype('int32')

In [44]:
arr = np.array([1, 2, 3], dtype = np.float64)   # dataType을 float64로 변경 후 생성

In [45]:
arr.dtype

dtype('float64')

In [46]:
arr.itemsize

8

In [47]:
arr[0].itemsize

8

In [48]:
arr

array([1., 2., 3.])

In [49]:
arr[0]   # 인덱싱

1.0

In [50]:
arr = np.array([[1, 2, 3], [3, 4, 5]])

In [51]:
arr[0, 1]   # 인덱싱

2

배열의 차원(축) 확인하고 변경하기

In [52]:
arr.shape

(2, 3)

In [53]:
arr.ndim   # ndim : 배열의 차원 확인

2

In [54]:
np.ndim(arr)

2

In [55]:
a = np.array([1, 2, 3])

In [56]:
a.ndim

1

In [57]:
a = np.array([[1, 2, 3]])

In [58]:
a.ndim

2

In [59]:
a = np.array([[[1, 2, 3]]])

In [60]:
a.ndim

3

In [61]:
a.shape

(1, 1, 3)

1차원배열을 다차원배열로 변경

1) shape 속성을 이용해서 변경

In [62]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [63]:
arr

array([1, 2, 3, 4, 5, 6])

배열명.shape = 행, 열

In [64]:
arr.shape = 2,3   # 1차원 배열의 요소의 개수가 딱 맞아야함

In [65]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
arr.shape = 3,2

In [67]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

2) resize함수를 이용

In [68]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [69]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [70]:
arr.resize(2, 4)   # 배열명.resize(행, 열)

In [71]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [72]:
arr.shape

(2, 4)

다차원배열을 1차원배열로 변경

In [73]:
arr = np.array([[1, 2, 3], [3, 4, 5]])

In [74]:
arr.shape

(2, 3)

In [75]:
arr.ndim

2

In [76]:
arr.shape = 6   # 1차원배열로 변경

In [77]:
arr

array([1, 2, 3, 3, 4, 5])

In [78]:
arr.shape = arr.size   # 배열의 개수만큼 열을 지정(배열의 값이 많을 때)

In [79]:
arr

array([1, 2, 3, 3, 4, 5])

In [80]:
arr = np.array([[1, 2, 3],[3, 4, 5]])

In [81]:
arr.resize(arr.size)

In [82]:
arr

array([1, 2, 3, 3, 4, 5])

배열 공유(view함수, reshape함수)

In [83]:
a1 = np.array([1, 2, 3])

In [84]:
a2 = np.array([1, 2, 3])

In [85]:
a1

array([1, 2, 3])

In [86]:
a2

array([1, 2, 3])

In [87]:
a1[0] = 5

In [88]:
a1

array([5, 2, 3])

In [89]:
a2

array([1, 2, 3])

In [90]:
b1 = np.array([1, 2, 3, 4])

In [91]:
b2 = b1   # 같은 메모리를 참조(배열의 공유)

In [92]:
b1

array([1, 2, 3, 4])

In [93]:
b2

array([1, 2, 3, 4])

In [94]:
b2[0] = 7

In [95]:
b2

array([7, 2, 3, 4])

In [96]:
b1

array([7, 2, 3, 4])

In [97]:
b1 is b2   # b1과 b2가 같은지 확인하는 연산

True

In [98]:
c1 = np.array([1, 2, 3])

In [99]:
c2 = c1.view()   # 하나의 배열을 공유해서 참조

In [100]:
c1

array([1, 2, 3])

In [101]:
c2

array([1, 2, 3])

In [102]:
c1[0] = 5

In [103]:
c1

array([5, 2, 3])

In [104]:
c2

array([5, 2, 3])

In [105]:
c1 is c2   # 같은것은 아님을 의미

False

In [106]:
d = np.array([1, 2, 3, 4, 5, 6])

In [107]:
e = d.reshape(6)   # reshape : shape를 다시 정의(차원변경 가능)

In [108]:
d

array([1, 2, 3, 4, 5, 6])

In [109]:
e

array([1, 2, 3, 4, 5, 6])

In [110]:
d is e

False

In [111]:
d.shape

(6,)

In [112]:
e.shape

(6,)

In [113]:
f = d.reshape(2, 3)

In [114]:
f

array([[1, 2, 3],
       [4, 5, 6]])

In [115]:
d[0] = 5

In [116]:
d

array([5, 2, 3, 4, 5, 6])

In [117]:
f

array([[5, 2, 3],
       [4, 5, 6]])

In [118]:
f[1, 1] = 7

In [119]:
f

array([[5, 2, 3],
       [4, 7, 6]])

In [120]:
d

array([5, 2, 3, 4, 7, 6])

In [121]:
aa = np.array([1, 2, 3, 4, 5, 6])

In [122]:
av = aa.view()

In [123]:
ar = aa.reshape(3, 2)

In [124]:
aa

array([1, 2, 3, 4, 5, 6])

In [125]:
av

array([1, 2, 3, 4, 5, 6])

In [126]:
ar

array([[1, 2],
       [3, 4],
       [5, 6]])

In [127]:
av.base   # base : 참조변수의 원본 찾는 속성, 원본을 출력

array([1, 2, 3, 4, 5, 6])

In [128]:
aa.base   # 원본일 경우 base속성은 아무것도 표시되지 않음

배열가공하기  
● 배열과 스칼라 간의 연산  
● 색인과 슬라이싱  
● 배열 전치와 축 바꾸기

In [129]:
a = np.array(45)

In [130]:
a.ndim

0

In [131]:
a.shape

()

In [132]:
b = np.array([45])

In [133]:
b.ndim

1

In [134]:
b.shape

(1,)

스칼라의 자료형

int, float, None, bool

In [135]:
10 

10

In [136]:
0b110   # b : 2진수

6

In [137]:
0o10   # o : 8진수

8

In [138]:
0x10   # x : 16진수

16

In [139]:
int(5)

5

In [140]:
int(5.4)

5

In [141]:
int("13")

13

In [142]:
float("12.5")

12.5

In [143]:
int(float("12.5"))   # 문자형 실수를 정수형으로 변환

12

In [144]:
int("10",16)   # "10" : 10진수

16

In [145]:
float(10)

10.0

In [146]:
float(12.5)

12.5

In [147]:
float("12.5")

12.5

In [148]:
d = None   # None : 값이 없음

In [149]:
d

In [150]:
True

True

In [151]:
False

False

In [152]:
bool(3>0)

True

In [153]:
bool(0)   # 0이면 False

False

In [154]:
bool(5)   # 0이 아니면 True

True

In [155]:
bool(-5)

True

In [156]:
bool(1.5)

True

In [157]:
bool(0.0)

False

In [158]:
bool('')   # 빈 문자열이면 False

False

In [159]:
bool('1')

True

In [160]:
bool('a')

True

In [161]:
bool([])

False

In [162]:
bool([1])

True

In [163]:
bool({})

False

In [164]:
bool({1})

True

In [165]:
bool({'name': 123})

True

배열과 스칼라 간의 연산

In [166]:
a = np.array([1, 2, 3, 4])

In [167]:
b = np.array(5)

In [168]:
c = a + b   # 브로드캐스팅 연산

In [169]:
c

array([6, 7, 8, 9])

배열의 색인과 슬라이싱

In [170]:
a = np.arange(11)

In [171]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [172]:
a[5]

5

In [173]:
a[2:6]

array([2, 3, 4, 5])

In [174]:
a[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [175]:
a[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [176]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [177]:
b = np.arange(2, 8)

In [178]:
b

array([2, 3, 4, 5, 6, 7])

In [179]:
c = np.arange(8, 2)

In [180]:
c   # 데이터가 생성이 안됨

array([], dtype=int32)

In [181]:
d = np.arange(0, 8, 2)   # 시작값, 종료값, 증감값

In [182]:
d

array([0, 2, 4, 6])

In [183]:
e = np.arange(1, 7)

In [184]:
e

array([1, 2, 3, 4, 5, 6])

In [185]:
np.reshape(e, (2, 3))

array([[1, 2, 3],
       [4, 5, 6]])

In [186]:
e[0:4]

array([1, 2, 3, 4])

In [187]:
e[0:4].reshape(2, 2)   # 슬라이싱 한 배열의 차원 변경

array([[1, 2],
       [3, 4]])

배열의 전치 : 배열의 행과 열을 변경

In [188]:
a = np.array([[1, 2, 3, 4], [2, 3, 4, 5]])

In [189]:
a.shape

(2, 4)

In [190]:
a

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [191]:
a.T   # T : 전치

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5]])

배열 전치 => 배열명.T or np.transpose(배열명)

In [192]:
a   # 변수에 담은게 아니므로 기존모양으로 출력

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [193]:
np.transpose(a)   # transpose: 전치

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5]])

배열 원소 빠르게 처리하기 => 유니버셜 함수  
- 유니버셜 함수 : 배열 원소 각각에 대해서 원소별로 작업을 해주는 것

In [194]:
a = np.array([5, -3, 7, -9, -2])

In [195]:
np.abs(a)

array([5, 3, 7, 9, 2])

In [196]:
b = np.array([1.534, 5.354, 2.212, 4.623])

In [197]:
np.round(b)   # 반올림하여 표시( = b.0)

array([2., 5., 2., 5.])

In [198]:
np.round(b, 1)   # 소수 1자리까지 표시

array([1.5, 5.4, 2.2, 4.6])

In [199]:
a = np.array([5, 6, 23, 9])

In [200]:
b = np.array([2, 11, 8, 4])

In [201]:
np.maximum(a, b)   # 두 배열의 같은 열의 값을 비교하여 큰 값을 가져옴

array([ 5, 11, 23,  9])

In [202]:
a + b

array([ 7, 17, 31, 13])

In [203]:
a = np.array([2, 5, 7, 1, 4, 3]).reshape(2, 3)

In [204]:
a

array([[2, 5, 7],
       [1, 4, 3]])

In [205]:
b = np.array([[2, 3, 4], [4, 5, 6]])

In [206]:
b

array([[2, 3, 4],
       [4, 5, 6]])

In [207]:
np.add(a,b)

array([[ 4,  8, 11],
       [ 5,  9,  9]])